Started logging messages at Wed Sep 08 20:47:28 2010
Info:    HW STEP v1.2.7
Info:    Reading D:\GCode\HS.stp
Info:    Processing D:\GCode\HS.stp
Info:    Transferring D:\GCode\HS.stp
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 2 B-reps in file
Info:    Found 170 B-rep faces in file
Info:    
Info:    Working on 295
Info:        Working on 4229
Info:            Created 
Info:        Working on 4231
Info:            Created 
Info:        Created 
Info:    Working on 284
Info:        Working on 293
Info:            Working on 6931
Info:                Working on 6929
Info:                    Working on 6875
Info:                        Created 
Info:                    Working on 1561
Info:                        Created 
Info:                    Working on 1562
Info:                        Created 
Info:                    Working on 6876
Info:                        Created 
Info:                    Working on 1563
Info:                        Created 
Info:                    Working on 1564
Info:                        Created 
Info:                    Working on 929
Info:                        Created 
Info:                    Working on 1565
Info:                        Created 
Info:                    Working on 1566
Info:                        Created 
Info:                    Working on 6877
Info:                        Created 
Info:                    Working on 1567
Info:                        Working on 377
Info:                            Created 
Info:                        Created 
Info:                    Working on 1568
Info:                        Created 
Info:                    Working on 1569
Info:                        Working on 378
Info:                            Created 
Info:                        Created 
Info:                    Working on 1570
Info:                        Created 
Info:                    Working on 6878
Info:                        Created 
Info:                    Working on 1571
Info:                        Created 
Info:                    Working on 1572
Info:                        Created 
Info:                    Working on 1573
Info:                        Created 
Info:                    Working on 1574
Info:                        Created 
Info:                    Working on 1575
Info:                        Created 
Info:                    Working on 1576
Info:                        Working on 379
Info:                            Created 
Info:                        Created 
Info:                    Working on 1577
Info:                        Created 
Info:                    Working on 1578
Info:                        Working on 380
Info:                            Created 
Info:                        Created 
Info:                    Working on 1579
Info:                        Created 
Info:                    Working on 1580
Info:                        Working on 381
Info:                            Created 
Info:                        Created 
Info:                    Working on 1581
Info:                        Created 
Info:                    Working on 1582
Info:                        Working on 382
Info:                            Created 
Info:                        Created 
Info:                    Working on 1583
Info:                        Created 
Info:                    Working on 6879
Info:                        Created 
Info:                    Working on 1584
Info:                        Created 
Info:                    Working on 1585
Info:                        Created 
Info:                    Working on 1586
Info:                        Created 
Info:                    Working on 930
Info:                        Created 
Info:                    Working on 931
Info:                        Created 
Info:                    Working on 1587
Info:                        Created 
Info:                    Working on 1588
Info:                        Created 
Info:                    Working on 1589
Info:                        Created 
Info:                    Working on 1590
Info:                        Created 
Info:                    Working on 932
Info:                        Created 
Info:                    Working on 1591
Info:                        Created 
Info:                    Working on 6880
Info:                        Created 
Info:                    Working on 1592
Info:                        Created 
Info:                    Working on 6881
Info:                        Created 
Info:                    Working on 1593
Info:                        Created 
Info:                    Working on 1594
Info:                        Created 
Info:                    Working on 1595
Info:                        Created 
Info:                    Working on 1596
Info:                        Created 
Info:                    Working on 1597
Info:                        Created 
Info:                    Working on 933
Info:                        Created 
Info:                    Working on 1598
Info:                        Created 
Info:                    Working on 934
Info:                        Created 
Info:                    Working on 1599
Info:                        Created 
Info:                    Working on 1600
Info:                        Created 
Info:                    Working on 1601
Info:                        Created 
Info:                    Working on 1602
Info:                        Created 
Info:                    Working on 1603
Info:                        Created 
Info:                    Working on 1604
Info:                        Created 
Info:                    Working on 1605
Info:                        Created 
Info:                    Working on 1606
Info:                        Created 
Info:                    Working on 1607
Info:                        Created 
Info:                    Working on 1608
Info:                        Created 
Info:                    Working on 1609
Info:                        Created 
Info:                    Working on 1610
Info:                        Created 
Info:                    Working on 1611
Info:                        Created 
Info:                    Working on 1612
Info:                        Created 
Info:                    Working on 1613
Info:                        Created 
Info:                    Working on 1614
Info:                        Created 
Info:                    Working on 1615
Info:                        Created 
Info:                    Working on 1616
Info:                        Created 
Info:                    Working on 1617
Info:                        Created 
Info:                    Working on 6882
Info:                        Created 
Info:                    Working on 1618
Info:                        Created 
Info:                    Working on 1619
Info:                        Created 
Info:                    Working on 1620
Info:                        Created 
Info:                    Working on 1621
Info:                        Created 
Info:                    Working on 1622
Info:                        Created 
Info:                    Working on 935
Info:                        Created 
Info:                    Working on 1623
Info:                        Created 
Info:                    Working on 936
Info:                        Created 
Info:                    Working on 1624
Info:                        Created 
Info:                    Working on 1625
Info:                        Created 
Info:                    Working on 1626
Info:                        Created 
Info:                    Working on 1627
Info:                        Created 
Info:                    Working on 1628
Info:                        Created 
Info:                    Working on 1629
Info:                        Created 
Info:                    Working on 1630
Info:                        Created 
Info:                    Working on 1631
Info:                        Created 
Info:                    Working on 1632
Info:                        Created 
Info:                    Working on 1633
Info:                        Created 
Info:                    Working on 1634
Info:                        Created 
Info:                    Working on 1635
Info:                        Created 
Info:                    Working on 1636
Info:                        Created 
Info:                    Working on 1637
Info:                        Created 
Info:                    Working on 1638
Info:                        Created 
Info:                    Working on 1639
Info:                        Created 
Info:                    Working on 1640
Info:                        Created 
Info:                    Working on 1641
Info:                        Created 
Info:                    Working on 1642
Info:                        Created 
Info:                    Working on 937
Info:                        Created 
Info:                    Working on 1643
Info:                        Created 
Info:                    Working on 1644
Info:                        Created 
Info:                    Working on 6883
Info:                        Created 
Info:                    Working on 1645
Info:                        Created 
Info:                    Working on 1646
Info:                        Created 
Info:                    Working on 1647
Info:                        Created 
Info:                    Working on 938
Info:                        Created 
Info:                    Working on 1648
Info:                        Created 
Info:                    Working on 1649
Info:                        Created 
Info:                    Working on 1650
Info:                        Created 
Info:                    Working on 1651
Info:                        Created 
Info:                    Working on 1652
Info:                        Created 
Info:                    Working on 1653
Info:                        Created 
Info:                    Working on 1654
Info:                        Created 
Info:                    Working on 1655
Info:                        Created 
Info:                    Working on 1656
Info:                        Created 
Info:                    Working on 1657
Info:                        Created 
Info:                    Working on 1658
Info:                        Created 
Info:                    Working on 1659
Info:                        Created 
Info:                    Working on 1660
Info:                        Created 
Info:                    Working on 1661
Info:                        Created 
Info:                    Working on 1662
Info:                        Created 
Info:                    Working on 1663
Info:                        Created 
Info:                    Working on 1664
Info:                        Created 
Info:                    Working on 1665
Info:                        Created 
Info:                    Working on 1666
Info:                        Created 
Info:                    Working on 1667
Info:                        Created 
Info:                    Working on 1668
Info:                        Created 
Info:                    Working on 939
Info:                        Created 
Info:                    Working on 1669
Info:                        Created 
Info:                    Working on 1670
Info:                        Created 
Info:                    Working on 6884
Info:                        Created 
Info:                    Working on 1671
Info:                        Created 
Info:                    Working on 1672
Info:                        Created 
Info:                    Working on 1673
Info:                        Created 
Info:                    Working on 940
Info:                        Created 
Info:                    Working on 1674
Info:                        Created 
Info:                    Working on 1675
Info:                        Created 
Info:                    Working on 1676
Info:                        Created 
Info:                    Working on 1677
Info:                        Created 
Info:                    Working on 1678
Info:                        Created 
Info:                    Working on 1679
Info:                        Created 
Info:                    Working on 1680
Info:                        Created 
Info:                    Working on 1681
Info:                        Created 
Info:                    Working on 1682
Info:                        Created 
Info:                    Working on 1683
Info:                        Created 
Info:                    Working on 1684
Info:                        Created 
Info:                    Working on 1685
Info:                        Created 
Info:                    Working on 1686
Info:                        Created 
Info:                    Working on 1687
Info:                        Created 
Info:                    Working on 1688
Info:                        Created 
Info:                    Working on 1689
Info:                        Created 
Info:                    Working on 1690
Info:                        Created 
Info:                    Working on 1691
Info:                        Created 
Info:                    Working on 1692
Info:                        Created 
Info:                    Working on 1693
Info:                        Created 
Info:                    Working on 1694
Info:                        Created 
Info:                    Working on 6885
Info:                        Created 
Info:                    Working on 1695
Info:                        Created 
Info:                    Working on 1696
Info:                        Created 
Info:                    Working on 941
Info:                        Created 
Info:                    Working on 6886
Info:                        Created 
Info:                    Working on 1697
Info:                        Created 
Info:                    Working on 1698
Info:                        Created 
Info:                    Working on 942
Info:                        Created 
Info:                    Working on 943
Info:                        Created 
Info:                    Working on 1699
Info:                        Created 
Info:                    Working on 6887
Info:                        Created 
Info:                    Working on 1700
Info:                        Created 
Info:                    Working on 944
Info:                        Created 
Info:                    Working on 1701
Info:                        Created 
Info:                    Working on 6888
Info:                        Created 
Info:                    Working on 1702
Info:                        Created 
Info:                    Working on 6889
Info:                        Created 
Info:                    Working on 1703
Info:                        Created 
Info:                    Working on 1704
Info:                        Created 
Info:                    Working on 945
Info:                        Created 
Info:                    Working on 6890
Info:                        Created 
Info:                    Working on 1705
Info:                        Created 
Info:                    Working on 1706
Info:                        Created 
Info:                    Working on 946
Info:                        Created 
Info:                    Working on 947
Info:                        Created 
Info:                    Working on 1707
Info:                        Created 
Info:                    Working on 6891
Info:                        Created 
Info:                    Working on 1708
Info:                        Created 
Info:                    Working on 948
Info:                        Created 
Info:                    Working on 1709
Info:                        Created 
Info:                    Working on 6892
Info:                        Created 
Info:                    Working on 1710
Info:                        Created 
Info:                    Working on 6893
Info:                        Created 
Info:                    Working on 1711
Info:                        Created 
Info:                    Working on 1712
Info:                        Created 
Info:                    Working on 949
Info:                        Created 
Info:                    Working on 6894
Info:                        Created 
Info:                    Working on 1713
Info:                        Created 
Info:                    Working on 1714
Info:                        Created 
Info:                    Working on 950
Info:                        Created 
Info:                    Working on 951
Info:                        Created 
Info:                    Working on 1715
Info:                        Created 
Info:                    Working on 6895
Info:                        Created 
Info:                    Working on 1716
Info:                        Created 
Info:                    Working on 952
Info:                        Created 
Info:                    Working on 1717
Info:                        Created 
Info:                    Working on 6896
Info:                        Created 
Info:                    Working on 1718
Info:                        Created 
Info:                    Working on 953
Info:                        Created 
Info:                    Working on 1719
Info:                        Created 
Info:                    Working on 1720
Info:                        Created 
Info:                    Working on 1721
Info:                        Created 
Info:                    Working on 1722
Info:                        Created 
Info:                    Working on 954
Info:                        Created 
Info:                    Working on 1723
Info:                        Created 
Info:                    Working on 1724
Info:                        Created 
Info:                    Working on 1725
Info:                        Created 
Info:                    Working on 6897
Info:                        Created 
Info:                    Working on 1726
Info:                        Created 
Info:                    Working on 1727
Info:                        Created 
Info:                    Working on 1728
Info:                        Created 
Info:                    Working on 955
Info:                        Created 
Info:                    Working on 1729
Info:                        Created 
Info:                    Working on 1730
Info:                        Created 
Info:                    Working on 1731
Info:                        Created 
Info:                    Working on 956
Info:                        Created 
Info:                    Working on 1732
Info:                        Created 
Info:                    Working on 1733
Info:                        Created 
Info:                    Working on 957
Info:                        Created 
Info:                    Working on 1734
Info:                        Created 
Info:                    Working on 1735
Info:                        Created 
Info:                    Working on 1736
Info:                        Created 
Info:                    Working on 958
Info:                        Created 
Info:                    Working on 1737
Info:                        Created 
Info:                    Working on 1738
Info:                        Created 
Info:                    Working on 1739
Info:                        Created 
Info:                    Working on 959
Info:                        Created 
Info:                    Working on 1740
Info:                        Created 
Info:                    Working on 1741
Info:                        Created 
Info:                    Working on 1742
Info:                        Created 
Info:                    Working on 960
Info:                        Created 
Info:                    Working on 1743
Info:                        Created 
Info:                    Working on 1744
Info:                        Created 
Info:                    Working on 1745
Info:                        Created 
Info:                    Working on 961
Info:                        Created 
Info:                    Working on 1746
Info:                        Created 
Info:                    Working on 1747
Info:                        Created 
Info:                    Working on 1748
Info:                        Created 
Info:                    Working on 962
Info:                        Created 
Info:                    Working on 1749
Info:                        Created 
Info:                    Working on 1750
Info:                        Created 
Info:                    Working on 1751
Info:                        Created 
Info:                    Working on 963
Info:                        Created 
Info:                    Working on 1752
Info:                        Created 
Info:                    Working on 1753
Info:                        Created 
Info:                    Working on 964
Info:                        Created 
Info:                    Working on 1754
Info:                        Created 
Info:                    Working on 1755
Info:                        Created 
Info:                    Working on 1756
Info:                        Created 
Info:                    Working on 965
Info:                        Created 
Info:                    Working on 1757
Info:                        Created 
Info:                    Working on 1758
Info:                        Created 
Info:                    Working on 1759
Info:                        Created 
Info:                    Working on 966
Info:                        Created 
Info:                    Working on 1760
Info:                        Created 
Info:                    Working on 1761
Info:                        Created 
Info:                    Working on 1762
Info:                        Created 
Info:                    Working on 967
Info:                        Created 
Info:                    Working on 1763
Info:                        Created 
Info:                    Working on 1764
Info:                        Created 
Info:                    Working on 1765
Info:                        Created 
Info:                    Working on 968
Info:                        Created 
Info:                    Working on 1766
Info:                        Created 
Info:                    Working on 1767
Info:                        Created 
Info:                    Working on 1768
Info:                        Created 
Info:                    Working on 969
Info:                        Created 
Info:                    Working on 1769
Info:                        Created 
Info:                    Working on 1770
Info:                        Created 
Info:                    Working on 1771
Info:                        Created 
Info:                    Working on 970
Info:                        Created 
Info:                    Working on 1772
Info:                        Created 
Info:                    Working on 1773
Info:                        Created 
Info:                    Working on 1774
Info:                        Created 
Info:                    Working on 971
Info:                        Created 
Info:                    Working on 1775
Info:                        Created 
Info:                    Working on 1776
Info:                        Created 
Info:                    Working on 1777
Info:                        Created 
Info:                    Working on 972
Info:                        Created 
Info:                    Working on 1778
Info:                        Created 
Info:                    Working on 1779
Info:                        Created 
Info:                    Working on 1780
Info:                        Created 
Info:                    Working on 973
Info:                        Created 
Info:                    Working on 1781
Info:                        Created 
Info:                    Working on 1782
Info:                        Created 
Info:                    Working on 1783
Info:                        Created 
Info:                    Working on 974
Info:                        Created 
Info:                    Working on 1784
Info:                        Created 
Info:                    Working on 1785
Info:                        Created 
Info:                    Working on 1786
Info:                        Created 
Info:                    Working on 975
Info:                        Created 
Info:                    Working on 1787
Info:                        Created 
Info:                    Working on 1788
Info:                        Created 
Info:                    Working on 1789
Info:                        Created 
Info:                    Working on 976
Info:                        Created 
Info:                    Working on 1790
Info:                        Created 
Info:                    Working on 1791
Info:                        Created 
Info:                    Working on 1792
Info:                        Created 
Info:                    Working on 977
Info:                        Created 
Info:                    Working on 1793
Info:                        Created 
Info:                    Working on 1794
Info:                        Created 
Info:                    Working on 978
Info:                        Created 
Info:                    Working on 1795
Info:                        Created 
Info:                    Working on 1796
Info:                        Created 
Info:                    Working on 1797
Info:                        Created 
Info:                    Working on 979
Info:                        Created 
Info:                    Working on 1798
Info:                        Created 
Info:                    Working on 1799
Info:                        Created 
Info:                    Working on 1800
Info:                        Created 
Info:                    Working on 6898
Info:                        Created 
Info:                    Working on 1801
Info:                        Created 
Info:                    Working on 1802
Info:                        Created 
Info:                    Working on 1803
Info:                        Created 
Info:                    Working on 980
Info:                        Created 
Info:                    Working on 1804
Info:                        Created 
Info:                    Working on 1805
Info:                        Created 
Info:                    Working on 1806
Info:                        Created 
Info:                    Working on 6899
Info:                        Created 
Info:                    Working on 1807
Info:                        Created 
Info:                    Working on 1808
Info:                        Created 
Info:                    Working on 1809
Info:                        Created 
Info:                    Working on 981
Info:                        Created 
Info:                    Working on 1810
Info:                        Created 
Info:                    Working on 1811
Info:                        Created 
Info:                    Working on 1812
Info:                        Created 
Info:                    Working on 6900
Info:                        Created 
Info:                    Working on 1813
Info:                        Created 
Info:                    Working on 1814
Info:                        Created 
Info:                    Working on 1815
Info:                        Created 
Info:                    Working on 982
Info:                        Created 
Info:                    Working on 1816
Info:                        Created 
Info:                    Working on 1817
Info:                        Created 
Info:                    Working on 1818
Info:                        Created 
Info:                    Working on 983
Info:                        Created 
Info:                    Working on 1819
Info:                        Created 
Info:                    Working on 1820
Info:                        Created 
Info:                    Working on 1821
Info:                        Created 
Info:                    Working on 984
Info:                        Created 
Info:                    Working on 1822
Info:                        Created 
Info:                    Working on 1823
Info:                        Created 
Info:                    Working on 6901
Info:                        Created 
Info:                    Working on 1824
Info:                        Created 
Info:                    Working on 1825
Info:                        Created 
Info:                    Working on 6902
Info:                        Created 
Info:                    Working on 1826
Info:                        Created 
Info:                    Working on 1827
Info:                        Created 
Info:                    Working on 985
Info:                        Created 
Info:                    Working on 986
Info:                        Created 
Info:                    Created 
Info:                Created 
Info:            Working on 4230
Info:                Created 
Info:            Created 
Info:        Created 
Info:    Working on 285
Info:        Working on 294
Info:            Working on 6932
Info:                Working on 6930
Info:                    Working on 6903
Info:                        Created 
Info:                    Working on 1828
Info:                        Created 
Info:                    Working on 1829
Info:                        Working on 383
Info:                            Created 
Info:                        Created 
Info:                    Working on 1830
Info:                        Created 
Info:                    Working on 1831
Info:                        Working on 384
Info:                            Created 
Info:                        Created 
Info:                    Working on 1832
Info:                        Created 
Info:                    Working on 987
Info:                        Created 
Info:                    Working on 1833
Info:                        Created 
Info:                    Working on 988
Info:                        Created 
Info:                    Working on 1834
Info:                        Created 
Info:                    Working on 1835
Info:                        Created 
Info:                    Working on 1836
Info:                        Created 
Info:                    Working on 1837
Info:                        Created 
Info:                    Working on 1838
Info:                        Created 
Info:                    Working on 1839
Info:                        Created 
Info:                    Working on 1840
Info:                        Created 
Info:                    Working on 1841
Info:                        Created 
Info:                    Working on 1842
Info:                        Created 
Info:                    Working on 989
Info:                        Created 
Info:                    Working on 1843
Info:                        Created 
Info:                    Working on 1844
Info:                        Created 
Info:                    Working on 6904
Info:                        Created 
Info:                    Working on 1845
Info:                        Working on 385
Info:                            Created 
Info:                        Created 
Info:                    Working on 1846
Info:                        Working on 386
Info:                            Created 
Info:                        Created 
Info:                    Working on 1847
Info:                        Created 
Info:                    Working on 6905
Info:                        Created 
Info:                    Working on 1848
Info:                        Created 
Info:                    Working on 1849
Info:                        Created 
Info:                    Working on 1850
Info:                        Created 
Info:                    Working on 1851
Info:                        Working on 387
Info:                            Created 
Info:                        Created 
Info:                    Working on 1852
Info:                        Created 
Info:                    Working on 1853
Info:                        Working on 388
Info:                            Created 
Info:                        Created 
Info:                    Working on 6906
Info:                        Created 
Info:                    Working on 1854
Info:                        Created 
Info:                    Working on 1855
Info:                        Created 
Info:                    Working on 990
Info:                        Created 
Info:                    Working on 991
Info:                        Created 
Info:                    Working on 1856
Info:                        Created 
Info:                    Working on 1857
Info:                        Created 
Info:                    Working on 6907
Info:                        Created 
Info:                    Working on 1858
Info:                        Created 
Info:                    Working on 1859
Info:                        Created 
Info:                    Working on 1860
Info:                        Created 
Info:                    Working on 1861
Info:                        Created 
Info:                    Working on 992
Info:                        Created 
Info:                    Working on 1862
Info:                        Created 
Info:                    Working on 1863
Info:                        Created 
Info:                    Working on 1864
Info:                        Created 
Info:                    Working on 1865
Info:                        Created 
Info:                    Working on 1866
Info:                        Created 
Info:                    Working on 1867
Info:                        Created 
Info:                    Working on 1868
Info:                        Created 
Info:                    Working on 1869
Info:                        Created 
Info:                    Working on 1870
Info:                        Created 
Info:                    Working on 1871
Info:                        Created 
Info:                    Working on 1872
Info:                        Created 
Info:                    Working on 1873
Info:                        Created 
Info:                    Working on 1874
Info:                        Created 
Info:                    Working on 1875
Info:                        Created 
Info:                    Working on 1876
Info:                        Created 
Info:                    Working on 1877
Info:                        Created 
Info:                    Working on 1878
Info:                        Created 
Info:                    Working on 1879
Info:                        Created 
Info:                    Working on 1880
Info:                        Created 
Info:                    Working on 1881
Info:                        Created 
Info:                    Working on 1882
Info:                        Created 
Info:                    Working on 1883
Info:                        Created 
Info:                    Working on 1884
Info:                        Created 
Info:                    Working on 1885
Info:                        Created 
Info:                    Working on 1886
Info:                        Created 
Info:                    Working on 1887
Info:                        Created 
Info:                    Working on 1888
Info:                        Created 
Info:                    Working on 1889
Info:                        Created 
Info:                    Working on 1890
Info:                        Created 
Info:                    Working on 1891
Info:                        Created 
Info:                    Working on 1892
Info:                        Created 
Info:                    Working on 1893
Info:                        Created 
Info:                    Working on 1894
Info:                        Created 
Info:                    Working on 993
Info:                        Created 
Info:                    Working on 1895
Info:                        Created 
Info:                    Working on 1896
Info:                        Created 
Info:                    Working on 6908
Info:                        Created 
Info:                    Working on 1897
Info:                        Created 
Info:                    Working on 1898
Info:                        Created 
Info:                    Working on 1899
Info:                        Created 
Info:                    Working on 1900
Info:                        Created 
Info:                    Working on 994
Info:                        Created 
Info:                    Working on 1901
Info:                        Created 
Info:                    Working on 1902
Info:                        Created 
Info:                    Working on 1903
Info:                        Created 
Info:                    Working on 1904
Info:                        Created 
Info:                    Working on 1905
Info:                        Created 
Info:                    Working on 1906
Info:                        Created 
Info:                    Working on 1907
Info:                        Created 
Info:                    Working on 1908
Info:                        Created 
Info:                    Working on 1909
Info:                        Created 
Info:                    Working on 1910
Info:                        Created 
Info:                    Working on 1911
Info:                        Created 
Info:                    Working on 1912
Info:                        Created 
Info:                    Working on 1913
Info:                        Created 
Info:                    Working on 1914
Info:                        Created 
Info:                    Working on 1915
Info:                        Created 
Info:                    Working on 1916
Info:                        Created 
Info:                    Working on 1917
Info:                        Created 
Info:                    Working on 1918
Info:                        Created 
Info:                    Working on 1919
Info:                        Created 
Info:                    Working on 1920
Info:                        Created 
Info:                    Working on 1921
Info:                        Created 
Info:                    Working on 1922
Info:                        Created 
Info:                    Working on 1923
Info:                        Created 
Info:                    Working on 1924
Info:                        Created 
Info:                    Working on 1925
Info:                        Created 
Info:                    Working on 1926
Info:                        Created 
Info:                    Working on 1927
Info:                        Created 
Info:                    Working on 1928
Info:                        Created 
Info:                    Working on 1929
Info:                        Created 
Info:                    Working on 1930
Info:                        Created 
Info:                    Working on 1931
Info:                        Created 
Info:                    Working on 1932
Info:                        Created 
Info:                    Working on 1933
Info:                        Created 
Info:                    Working on 995
Info:                        Created 
Info:                    Working on 1934
Info:                        Created 
Info:                    Working on 6909
Info:                        Created 
Info:                    Working on 1935
Info:                        Created 
Info:                    Working on 1936
Info:                        Created 
Info:                    Working on 996
Info:                        Created 
Info:                    Working on 1937
Info:                        Created 
Info:                    Working on 6910
Info:                        Created 
Info:                    Working on 1938
Info:                        Created 
Info:                    Working on 1939
Info:                        Created 
Info:                    Working on 997
Info:                        Created 
Info:                    Working on 1940
Info:                        Created 
Info:                    Working on 6911
Info:                        Created 
Info:                    Working on 1941
Info:                        Created 
Info:                    Working on 1942
Info:                        Created 
Info:                    Working on 998
Info:                        Created 
Info:                    Working on 1943
Info:                        Created 
Info:                    Working on 6912
Info:                        Created 
Info:                    Working on 1944
Info:                        Created 
Info:                    Working on 1945
Info:                        Created 
Info:                    Working on 999
Info:                        Created 
Info:                    Working on 1946
Info:                        Created 
Info:                    Working on 6913
Info:                        Created 
Info:                    Working on 1947
Info:                        Created 
Info:                    Working on 1948
Info:                        Created 
Info:                    Working on 1000
Info:                        Created 
Info:                    Working on 1949
Info:                        Created 
Info:                    Working on 6914
Info:                        Created 
Info:                    Working on 1950
Info:                        Created 
Info:                    Working on 1951
Info:                        Created 
Info:                    Working on 1001
Info:                        Created 
Info:                    Working on 1952
Info:                        Created 
Info:                    Working on 6915
Info:                        Created 
Info:                    Working on 1953
Info:                        Created 
Info:                    Working on 1954
Info:                        Created 
Info:                    Working on 1002
Info:                        Created 
Info:                    Working on 1955
Info:                        Created 
Info:                    Working on 6916
Info:                        Created 
Info:                    Working on 1956
Info:                        Created 
Info:                    Working on 1957
Info:                        Created 
Info:                    Working on 1003
Info:                        Created 
Info:                    Working on 1958
Info:                        Created 
Info:                    Working on 6917
Info:                        Created 
Info:                    Working on 1959
Info:                        Created 
Info:                    Working on 1960
Info:                        Created 
Info:                    Working on 1004
Info:                        Created 
Info:                    Working on 1961
Info:                        Created 
Info:                    Working on 6918
Info:                        Created 
Info:                    Working on 1962
Info:                        Created 
Info:                    Working on 1963
Info:                        Created 
Info:                    Working on 1005
Info:                        Created 
Info:                    Working on 1964
Info:                        Created 
Info:                    Working on 6919
Info:                        Created 
Info:                    Working on 1965
Info:                        Created 
Info:                    Working on 1966
Info:                        Created 
Info:                    Working on 1006
Info:                        Created 
Info:                    Working on 1967
Info:                        Created 
Info:                    Working on 6920
Info:                        Created 
Info:                    Working on 1968
Info:                        Created 
Info:                    Working on 1969
Info:                        Created 
Info:                    Working on 1007
Info:                        Created 
Info:                    Working on 1970
Info:                        Created 
Info:                    Working on 6921
Info:                        Created 
Info:                    Working on 1971
Info:                        Created 
Info:                    Working on 1972
Info:                        Created 
Info:                    Working on 1008
Info:                        Created 
Info:                    Working on 1973
Info:                        Created 
Info:                    Working on 6922
Info:                        Created 
Info:                    Working on 1974
Info:                        Created 
Info:                    Working on 1975
Info:                        Created 
Info:                    Working on 1009
Info:                        Created 
Info:                    Working on 1976
Info:                        Created 
Info:                    Working on 1977
Info:                        Created 
Info:                    Working on 1978
Info:                        Created 
Info:                    Working on 1979
Info:                        Created 
Info:                    Working on 1010
Info:                        Created 
Info:                    Working on 1980
Info:                        Created 
Info:                    Working on 1981
Info:                        Created 
Info:                    Working on 1982
Info:                        Created 
Info:                    Working on 6923
Info:                        Created 
Info:                    Working on 1983
Info:                        Created 
Info:                    Working on 1984
Info:                        Created 
Info:                    Working on 1985
Info:                        Created 
Info:                    Working on 1011
Info:                        Created 
Info:                    Working on 1986
Info:                        Created 
Info:                    Working on 1987
Info:                        Created 
Info:                    Working on 1988
Info:                        Created 
Info:                    Working on 1012
Info:                        Created 
Info:                    Working on 1989
Info:                        Created 
Info:                    Working on 1990
Info:                        Created 
Info:                    Working on 1991
Info:                        Created 
Info:                    Working on 1013
Info:                        Created 
Info:                    Working on 1992
Info:                        Created 
Info:                    Working on 1993
Info:                        Created 
Info:                    Working on 1994
Info:                        Created 
Info:                    Working on 6924
Info:                        Created 
Info:                    Working on 1995
Info:                        Created 
Info:                    Working on 1996
Info:                        Created 
Info:                    Working on 1997
Info:                        Created 
Info:                    Working on 1014
Info:                        Created 
Info:                    Working on 1998
Info:                        Created 
Info:                    Working on 1999
Info:                        Created 
Info:                    Working on 2000
Info:                        Created 
Info:                    Working on 1015
Info:                        Created 
Info:                    Working on 2001
Info:                        Created 
Info:                    Working on 2002
Info:                        Created 
Info:                    Working on 1016
Info:                        Created 
Info:                    Working on 2003
Info:                        Created 
Info:                    Working on 2004
Info:                        Created 
Info:                    Working on 2005
Info:                        Created 
Info:                    Working on 1017
Info:                        Created 
Info:                    Working on 2006
Info:                        Created 
Info:                    Working on 2007
Info:                        Created 
Info:                    Working on 2008
Info:                        Created 
Info:                    Working on 1018
Info:                        Created 
Info:                    Working on 2009
Info:                        Created 
Info:                    Working on 2010
Info:                        Created 
Info:                    Working on 2011
Info:                        Created 
Info:                    Working on 1019
Info:                        Created 
Info:                    Working on 2012
Info:                        Created 
Info:                    Working on 2013
Info:                        Created 
Info:                    Working on 2014
Info:                        Created 
Info:                    Working on 1020
Info:                        Created 
Info:                    Working on 2015
Info:                        Created 
Info:                    Working on 2016
Info:                        Created 
Info:                    Working on 2017
Info:                        Created 
Info:                    Working on 1021
Info:                        Created 
Info:                    Working on 2018
Info:                        Created 
Info:                    Working on 2019
Info:                        Created 
Info:                    Working on 2020
Info:                        Created 
Info:                    Working on 1022
Info:                        Created 
Info:                    Working on 2021
Info:                        Created 
Info:                    Working on 2022
Info:                        Created 
Info:                    Working on 2023
Info:                        Created 
Info:                    Working on 1023
Info:                        Created 
Info:                    Working on 2024
Info:                        Created 
Info:                    Working on 2025
Info:                        Created 
Info:                    Working on 2026
Info:                        Created 
Info:                    Working on 1024
Info:                        Created 
Info:                    Working on 2027
Info:                        Created 
Info:                    Working on 2028
Info:                        Created 
Info:                    Working on 2029
Info:                        Created 
Info:                    Working on 1025
Info:                        Created 
Info:                    Working on 2030
Info:                        Created 
Info:                    Working on 2031
Info:                        Created 
Info:                    Working on 2032
Info:                        Created 
Info:                    Working on 1026
Info:                        Created 
Info:                    Working on 2033
Info:                        Created 
Info:                    Working on 2034
Info:                        Created 
Info:                    Working on 2035
Info:                        Created 
Info:                    Working on 1027
Info:                        Created 
Info:                    Working on 2036
Info:                        Created 
Info:                    Working on 2037
Info:                        Created 
Info:                    Working on 2038
Info:                        Created 
Info:                    Working on 1028
Info:                        Created 
Info:                    Working on 2039
Info:                        Created 
Info:                    Working on 2040
Info:                        Created 
Info:                    Working on 2041
Info:                        Created 
Info:                    Working on 1029
Info:                        Created 
Info:                    Working on 2042
Info:                        Created 
Info:                    Working on 2043
Info:                        Created 
Info:                    Working on 2044
Info:                        Created 
Info:                    Working on 1030
Info:                        Created 
Info:                    Working on 2045
Info:                        Created 
Info:                    Working on 2046
Info:                        Created 
Info:                    Working on 1031
Info:                        Created 
Info:                    Working on 2047
Info:                        Created 
Info:                    Working on 2048
Info:                        Created 
Info:                    Working on 2049
Info:                        Created 
Info:                    Working on 1032
Info:                        Created 
Info:                    Working on 2050
Info:                        Created 
Info:                    Working on 2051
Info:                        Created 
Info:                    Working on 2052
Info:                        Created 
Info:                    Working on 1033
Info:                        Created 
Info:                    Working on 2053
Info:                        Created 
Info:                    Working on 2054
Info:                        Created 
Info:                    Working on 2055
Info:                        Created 
Info:                    Working on 1034
Info:                        Created 
Info:                    Working on 2056
Info:                        Created 
Info:                    Working on 2057
Info:                        Created 
Info:                    Working on 2058
Info:                        Created 
Info:                    Working on 1035
Info:                        Created 
Info:                    Working on 2059
Info:                        Created 
Info:                    Working on 2060
Info:                        Created 
Info:                    Working on 2061
Info:                        Created 
Info:                    Working on 1036
Info:                        Created 
Info:                    Working on 2062
Info:                        Created 
Info:                    Working on 2063
Info:                        Created 
Info:                    Working on 2064
Info:                        Created 
Info:                    Working on 1037
Info:                        Created 
Info:                    Working on 2065
Info:                        Created 
Info:                    Working on 2066
Info:                        Created 
Info:                    Working on 2067
Info:                        Created 
Info:                    Working on 1038
Info:                        Created 
Info:                    Working on 2068
Info:                        Created 
Info:                    Working on 2069
Info:                        Created 
Info:                    Working on 6925
Info:                        Created 
Info:                    Working on 2070
Info:                        Created 
Info:                    Working on 2071
Info:                        Created 
Info:                    Working on 2072
Info:                        Created 
Info:                    Working on 1039
Info:                        Created 
Info:                    Working on 2073
Info:                        Created 
Info:                    Working on 2074
Info:                        Created 
Info:                    Working on 2075
Info:                        Created 
Info:                    Working on 6926
Info:                        Created 
Info:                    Working on 2076
Info:                        Created 
Info:                    Working on 2077
Info:                        Created 
Info:                    Working on 2078
Info:                        Created 
Info:                    Working on 1040
Info:                        Created 
Info:                    Working on 2079
Info:                        Created 
Info:                    Working on 2080
Info:                        Created 
Info:                    Working on 2081
Info:                        Created 
Info:                    Working on 1041
Info:                        Created 
Info:                    Working on 2082
Info:                        Created 
Info:                    Working on 2083
Info:                        Created 
Info:                    Working on 2084
Info:                        Created 
Info:                    Working on 1042
Info:                        Created 
Info:                    Working on 2085
Info:                        Created 
Info:                    Working on 2086
Info:                        Created 
Info:                    Working on 6927
Info:                        Created 
Info:                    Working on 2087
Info:                        Created 
Info:                    Working on 2088
Info:                        Created 
Info:                    Working on 6928
Info:                        Created 
Info:                    Working on 2089
Info:                        Created 
Info:                    Working on 2090
Info:                        Created 
Info:                    Working on 1043
Info:                        Created 
Info:                    Working on 1044
Info:                        Created 
Info:                    Created 
Info:                Created 
Info:            Working on 4232
Info:                Created 
Info:            Created 
Info:        Created 
Info:    Finished with D:\GCode\HS.stp
