Started logging messages at Tue Nov 29 16:10:13 2011
Info:    HW IGES v1.5.7
Info:    Reading D:\GCode\holder.igs
Info:    Reading D:\GCode\holder.igs
Info:    File completely read
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 46 trimmed surfaces in file
Info:    Found 0 B-reps in file
Info:    Found 0 B-rep faces in file
Info:    
Info:    Processing D:\GCode\holder.igs
Info:    IGES/Nlib processing done
Info:    Transferring D:\GCode\holder.igs
Info:    Finished with D:\GCode\holder.igs
